package net.elpixedge.core.combat;

import net.elpixedge.core.ElpixEdge;
import net.elpixedge.core.Module;
import net.elpixedge.core.player.PlayerModule;
import net.elpixedge.core.player.PlayerProfile;
import net.elpixedge.core.utils.Keys;
import net.elpixedge.core.utils.StatType;
import org.bukkit.*;
import org.bukkit.attribute.Attribute;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.*;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.FireworkMeta;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.scheduler.BukkitRunnable;
import org.bukkit.util.Vector;

import java.util.*;

/**
 * MagicModule — handles:
 * - Grimoire (Off-hand): Right-Click casts active scroll spell;
 * Shift+Right-Click cycles scrolls.
 * - Magic Staff (Main-hand): Left-Click fires staff ability (ARCANE_BULLET).
 * - Spell Scroll casting logic (ASHEN_SPARK, LITTLE_PHOENIX).
 * - Spell Scroll casting logic (ASHEN_SPARK, LITTLE_PHOENIX).
 *
 * All magic attack damage scales from the player's MAGIC_DAMAGE stat.
 * GCD for magic abilities is applied at 50% of the configured value (magic
 * discount rule).
 *
 * Grimoire stores scrolls as a comma-separated list of scroll type IDs in PDC
 * key "grimoire_scrolls".
 * Active scroll index is stored in "grimoire_active" (INTEGER).
 * Max slots are stored in "grimoire_slots" (INTEGER).
 *
 * The Grimoire carries the "magic_dmg_item" byte tag so PlayerModule includes
 * its stats.
 */
public class MagicModule implements Module, Listener {

    private final ElpixEdge plugin;

    // Magic GCD discount: all magic skill GCDs run at 50% of configured value
    private static final double MAGIC_GCD_MULT = 0.5;

    // Debounce to prevent ghost left-clicks from firing when interacting with
    // bundles (Grimoire)
    private final Map<UUID, Long> lastRightClick = new HashMap<>();

    public MagicModule(ElpixEdge plugin) {
        this.plugin = plugin;
    }

    @Override
    public void onEnable() {
        plugin.getServer().getPluginManager().registerEvents(this, plugin);
        plugin.getLogger().info("MagicModule enabled successfully.");
    }

    @Override
    public void onDisable() {
    }

    // ==========================================
    // Main-hand Staff — Left Click
    // ==========================================
    @EventHandler(priority = EventPriority.HIGH)
    public void onStaffInteract(PlayerInteractEvent event) {
        // Main-hand left-click only — prevents off-hand event from triggering staff
        // cast
        if (event.getHand() != EquipmentSlot.HAND)
            return;

        if (isMenuItem(event.getPlayer().getInventory().getItemInMainHand()) || isMenuItem(event.getPlayer().getInventory().getItemInOffHand())) {
            event.setCancelled(true);
            return;
        }

        // Explicitly cancel and reject any right-click actions immediately to prevent
        // Arcane Bullet leak
        if (event.getAction() == Action.RIGHT_CLICK_AIR || event.getAction() == Action.RIGHT_CLICK_BLOCK) {
            lastRightClick.put(event.getPlayer().getUniqueId(), System.currentTimeMillis());
            ItemStack item = event.getItem();
            if (item != null && item.hasItemMeta() && item.getItemMeta().getPersistentDataContainer()
                    .has(Keys.magicDmgItem, PersistentDataType.BYTE)) {
                event.setCancelled(true);
            }
            return;
        }

        if (event.getAction() != Action.LEFT_CLICK_AIR && event.getAction() != Action.LEFT_CLICK_BLOCK)
            return;

        // Debounce: If a right-click was processed very recently (within 200ms), ignore
        // this left-click
        // This stops "ghost" left-clicks generated by the client/server when using a
        // Bundle in the offhand.
        long lastRc = lastRightClick.getOrDefault(event.getPlayer().getUniqueId(), 0L);
        if (System.currentTimeMillis() - lastRc < 200) {
            return;
        }

        Player p = event.getPlayer();
        ItemStack item = p.getInventory().getItemInMainHand(); // Strictly read from main hand
        if (item == null || item.getType() == Material.AIR || !item.hasItemMeta())
            return;

        ItemMeta meta = item.getItemMeta();
        // Must have magic_dmg_item tag AND a skill — this is a magic staff
        if (!meta.getPersistentDataContainer().has(Keys.magicDmgItem, PersistentDataType.BYTE))
            return;
        if (!meta.getPersistentDataContainer().has(Keys.skill, PersistentDataType.STRING))
            return;

        // Block interaction priority
        if (event.getAction() == Action.RIGHT_CLICK_BLOCK && event.getClickedBlock() != null) {
            if (event.getClickedBlock().getType().isInteractable() && !p.isSneaking())
                return;
        }

        String skillId = meta.getPersistentDataContainer().get(Keys.skill, PersistentDataType.STRING);
        event.setCancelled(true);

        PlayerModule playerMod = ElpixEdge.getInstance().getModule(PlayerModule.class);
        PlayerProfile profile = playerMod != null ? playerMod.getProfile(p) : null;
        if (profile == null)
            return;

        int manaCost = meta.getPersistentDataContainer().getOrDefault(Keys.manaCost, PersistentDataType.INTEGER, 5);

        // GCD at 50%
        long baseGcd = plugin.getConfig().getLong("game_settings.active_skills_gcd." + skillId.toLowerCase(), 1000L);
        long gcd = (long) (baseGcd * MAGIC_GCD_MULT);
        double gcdReduc = profile.getStats().getOrDefault(StatType.GCD_REDUC, 0.0);
        gcd = (long) (gcd * (1.0 - gcdReduc));

        if (!checkAndConsumeResources(p, profile, manaCost, gcd, skillId))
            return;

        p.setCooldown(item.getType(), (int) (gcd / 50));

        if (skillId.equalsIgnoreCase("ARCANE_BULLET")) {
            castArcaneBullet(p, profile, item);
        }
    }

    // ==========================================
    // Grimoire Off-hand — Right Click / Shift+Right Click
    // ==========================================
    @EventHandler(priority = EventPriority.HIGH)
    public void onGrimoireInteract(PlayerInteractEvent event) {
        // Off-hand only — grimoire is always in the off-hand
        if (event.getHand() != EquipmentSlot.OFF_HAND)
            return;
        
        if (isMenuItem(event.getPlayer().getInventory().getItemInMainHand()) || isMenuItem(event.getPlayer().getInventory().getItemInOffHand())) {
            event.setCancelled(true);
            return;
        }

        // Right-click air or block
        if (event.getAction() != Action.RIGHT_CLICK_AIR && event.getAction() != Action.RIGHT_CLICK_BLOCK)
            return;

        Player p = event.getPlayer();
        ItemStack item = p.getInventory().getItemInOffHand(); // always read from actual off-hand slot
        if (!isGrimoire(item))
            return;

        ItemMeta meta = item.getItemMeta();

        // Block interaction priority
        if (event.getAction() == Action.RIGHT_CLICK_BLOCK && event.getClickedBlock() != null) {
            if (event.getClickedBlock().getType().isInteractable() && !p.isSneaking())
                return;
        }

        // Cancel bundle emptying/right-click action
        event.setCancelled(true);

        PlayerModule playerMod = ElpixEdge.getInstance().getModule(PlayerModule.class);
        PlayerProfile profile = playerMod != null ? playerMod.getProfile(p) : null;
        if (profile == null)
            return;

        if (p.isSneaking()) {
            // Shift+Right-Click: cycle active scroll
            cycleGrimoireScroll(p, item, meta);
            event.setCancelled(true);
            return;
        }

        // Right-Click: cast the active scroll
        List<ItemStack> scrollItems = getGrimoireScrollItems(meta);
        if (scrollItems.isEmpty()) {
            profile.setActionBarMessage(ChatColor.GRAY + "No scrolls stored in grimoire.", 1500);
            return;
        }
        int activeIdx = meta.getPersistentDataContainer().getOrDefault(Keys.grimoireActive, PersistentDataType.INTEGER,
                0);
        if (activeIdx < 0 || activeIdx >= scrollItems.size())
            activeIdx = 0;

        ItemStack scrollItem = scrollItems.get(activeIdx);
        if (scrollItem == null || !scrollItem.hasItemMeta())
            return;

        // Use customItemId to look up the scroll config
        String scrollId = scrollItem.getItemMeta().getPersistentDataContainer().get(Keys.customItemId,
                PersistentDataType.STRING);
        if (scrollId == null)
            return;

        ConfigurationSection scrollSec = plugin.getConfig().getConfigurationSection("scrolls." + scrollId);
        if (scrollSec == null) {
            profile.setActionBarMessage(ChatColor.RED + "Unknown scroll config: " + scrollId, 1500);
            return;
        }

        String spellType = scrollSec.getString("spell_type", "");
        int manaCost = scrollSec.getInt("mana_cost", 30);
        long baseGcd = plugin.getConfig().getLong("game_settings.active_skills_gcd." + spellType.toLowerCase(), 1000L);
        long gcd = (long) (baseGcd * MAGIC_GCD_MULT);
        double gcdReduc = profile.getStats().getOrDefault(StatType.GCD_REDUC, 0.0);
        gcd = (long) (gcd * (1.0 - gcdReduc));

        // Check for Aimbot on the Grimoire itself to apply to spells
        int aimTier = 0;
        for (int t = 3; t >= 1; t--) {
            if (meta.getPersistentDataContainer().has(new NamespacedKey(plugin, "ench_aiming_" + t),
                    PersistentDataType.BYTE)) {
                aimTier = t;
                break;
            }
        }

        if (!checkAndConsumeResources(p, profile, manaCost, gcd, spellType))
            return;

        p.setCooldown(p.getInventory().getItemInMainHand().getType(), (int) (gcd / 50));
        p.setCooldown(item.getType(), (int) (gcd / 50));

        boolean success = dispatchScroll(p, profile, spellType, aimTier);

        if (success) {
            // If consumable and cast succeeded, remove the scroll from the grimoire
            boolean isConsumable = scrollSec.getBoolean("consumable", false);
            if (isConsumable) {
                ItemStack stack = scrollItems.get(activeIdx);
                if (stack.getAmount() > 1) {
                    stack.setAmount(stack.getAmount() - 1);
                } else {
                    scrollItems.remove(activeIdx);
                }
                // Clamp active index
                int newActive = Math.min(activeIdx, Math.max(0, scrollItems.size() - 1));
                saveGrimoireScrollItems(item, meta, scrollItems, newActive);
                p.updateInventory();
                profile.setActionBarMessage(ChatColor.GOLD + "Scroll consumed!", 500);
            }
        }
    }

    // ==========================================
    // Standalone Scroll Off-hand — Right Click
    // ==========================================
    @EventHandler(priority = EventPriority.HIGH)
    public void onStandaloneScrollInteract(PlayerInteractEvent event) {
        if (event.getHand() != EquipmentSlot.OFF_HAND)
            return;
            
        if (isMenuItem(event.getPlayer().getInventory().getItemInMainHand()) || isMenuItem(event.getPlayer().getInventory().getItemInOffHand())) {
            event.setCancelled(true);
            return;
        }

        if (event.getAction() != Action.RIGHT_CLICK_AIR && event.getAction() != Action.RIGHT_CLICK_BLOCK)
            return;

        Player p = event.getPlayer();
        ItemStack item = p.getInventory().getItemInOffHand();
        if (item == null || !item.hasItemMeta())
            return;

        ItemMeta meta = item.getItemMeta();
        if (!meta.getPersistentDataContainer().has(Keys.scrollType, PersistentDataType.STRING))
            return;

        // Make sure it's NOT a grimoire
        if (isGrimoire(item))
            return;

        if (event.getAction() == Action.RIGHT_CLICK_BLOCK && event.getClickedBlock() != null) {
            if (event.getClickedBlock().getType().isInteractable() && !p.isSneaking())
                return;
        }

        event.setCancelled(true);

        PlayerModule playerMod = ElpixEdge.getInstance().getModule(PlayerModule.class);
        PlayerProfile profile = playerMod != null ? playerMod.getProfile(p) : null;
        if (profile == null)
            return;

        String scrollId = meta.getPersistentDataContainer().get(Keys.customItemId, PersistentDataType.STRING);
        if (scrollId == null)
            return;

        ConfigurationSection scrollSec = plugin.getConfig().getConfigurationSection("scrolls." + scrollId);
        if (scrollSec == null)
            return;

        String spellType = scrollSec.getString("spell_type", "");
        int manaCost = scrollSec.getInt("mana_cost", 30);
        long baseGcd = plugin.getConfig().getLong("game_settings.active_skills_gcd." + spellType.toLowerCase(), 1000L);
        long gcd = (long) (baseGcd * MAGIC_GCD_MULT);
        double gcdReduc = profile.getStats().getOrDefault(StatType.GCD_REDUC, 0.0);
        gcd = (long) (gcd * (1.0 - gcdReduc));

        if (!checkAndConsumeResources(p, profile, manaCost, gcd, spellType))
            return;

        boolean success = dispatchScroll(p, profile, spellType, 0);

        if (success) {
            p.setCooldown(item.getType(), (int) (gcd / 50));
            boolean isConsumable = scrollSec.getBoolean("consumable", false);
            if (isConsumable) {
                if (item.getAmount() > 1) {
                    item.setAmount(item.getAmount() - 1);
                } else {
                    p.getInventory().setItemInOffHand(null);
                }
                p.updateInventory();
                profile.setActionBarMessage(ChatColor.GOLD + "Scroll consumed!", 1500);
            }
        }
    }

    // ==========================================
    // Spell Dispatch
    // Returns true if the spell was successfully cast.
    // ==========================================
    private boolean dispatchScroll(Player p, PlayerProfile profile, String type, int aimTier) {
        if (type == null)
            return false;
        String spellType = type.trim().toUpperCase();

        if (spellType.equals("ASHEN_SPARK")) {
            castAshenSpark(p, profile, aimTier);
            return true;
        } else if (spellType.equals("LITTLE_PHOENIX")) {
            castLittlePhoenix(p, profile);
            return true;
        }
        profile.setActionBarMessage(ChatColor.RED + "Unknown spell: " + type, 1500);
        return false;
    }

    // ==========================================
    // GCD + Mana gating helper
    // Returns true if both checks pass (resources consumed).
    // ==========================================
    private boolean checkAndConsumeResources(Player p, PlayerProfile profile, int manaCost, long gcd,
            String spellName) {
        long now = System.currentTimeMillis();

        if (profile.getGlobalCooldown() > 0 && now < profile.getGlobalCooldown()) {
            double timeLeft = (profile.getGlobalCooldown() - now) / 1000.0;
            profile.setActionBarMessage(ChatColor.RED + "Cooldown: " + String.format("%.1f", timeLeft) + "s", 1000);
            return false;
        }

        if (profile.getCurrentMana() < manaCost) {
            profile.setActionBarMessage(ChatColor.RED + "Not enough Mana!", 1500);
            return false;
        }

        profile.setGlobalCooldown(now + gcd);
        profile.setCurrentMana(profile.getCurrentMana() - manaCost);
        return true;
    }

    // ==========================================
    // SPELL: Arcane Bullet (Staff)
    // Fast straight projectile scaling off MAGIC_DAMAGE.
    // ==========================================
    private void castArcaneBullet(Player p, PlayerProfile profile, ItemStack staff) {
        double magicDmg = profile.getStats().getOrDefault(StatType.MAGIC_DAMAGE, 1.0);

        // Fire a snowball-type projectile with enhanced speed and NO GRAVITY
        org.bukkit.entity.Snowball bullet = p.launchProjectile(org.bukkit.entity.Snowball.class);
        Vector dir = p.getEyeLocation().getDirection().normalize().multiply(3.5);
        bullet.setVelocity(dir);
        bullet.setGravity(false); // No gravity as requested

        // Tag with override damage so CombatModule picks it up
        double bulletDmg = magicDmg
                * plugin.getConfig().getDouble("magic_staves.whispering_staff.damage_multiplier", 1.5);
        bullet.getPersistentDataContainer().set(Keys.dmg, PersistentDataType.DOUBLE, bulletDmg);

        // Aimbot support for staff
        CombatModule combat = plugin.getModule(CombatModule.class);
        if (combat != null && staff.hasItemMeta()) {
            ItemMeta meta = staff.getItemMeta();
            int aimTier = 0;
            for (int t = 3; t >= 1; t--) {
                if (meta.getPersistentDataContainer().has(new NamespacedKey(plugin, "ench_aiming_" + t),
                        PersistentDataType.BYTE)) {
                    aimTier = t;
                    break;
                }
            }
            if (aimTier > 0) {
                combat.startHomingTask(bullet, aimTier);
            } else {
                new BukkitRunnable() {
                    @Override
                    public void run() {
                        if (!bullet.isDead() && bullet.isValid())
                            bullet.remove();
                    }
                }.runTaskLater(plugin, 100L);
            }
        }

        p.getWorld().spawnParticle(Particle.WITCH,
                p.getEyeLocation().add(p.getEyeLocation().getDirection().multiply(1.2)), 20, 0.1, 0.1, 0.1, 0.05);
        p.getWorld().spawnParticle(Particle.ENCHANTED_HIT,
                p.getEyeLocation().add(p.getEyeLocation().getDirection().multiply(1.2)), 10, 0.2, 0.2, 0.2, 0.02);
        p.playSound(p.getLocation(), Sound.ENTITY_WITCH_THROW, 1f, 1.6f);

        // Particle Trail Task
        new org.bukkit.scheduler.BukkitRunnable() {
            @Override
            public void run() {
                if (bullet.isDead() || !bullet.isValid()) {
                    cancel();
                    return;
                }
                bullet.getWorld().spawnParticle(Particle.WITCH, bullet.getLocation(), 3, 0.02, 0.02, 0.02, 0.01);
                bullet.getWorld().spawnParticle(Particle.SOUL_FIRE_FLAME, bullet.getLocation(), 1, 0.01, 0.01, 0.01, 0);
            }
        }.runTaskTimer(plugin, 1L, 1L);

        profile.setActionBarMessage(ChatColor.LIGHT_PURPLE + "✧ Arcane Bullet!", 1500);
    }

    // ==========================================
    // SPELL: Ashen Spark (Scroll)
    // Short-range fire projectile scaling off MAGIC_DAMAGE.
    // ==========================================
    private void castAshenSpark(Player p, PlayerProfile profile, int aimTier) {
        double magicDmg = profile.getStats().getOrDefault(StatType.MAGIC_DAMAGE, 1.0);
        double spellDmg = magicDmg * plugin.getConfig().getDouble("scrolls.ashen_spark.damage_multiplier", 2.0);

        org.bukkit.entity.Snowball spark = p.launchProjectile(org.bukkit.entity.Snowball.class);
        Vector dir = p.getEyeLocation().getDirection().normalize().multiply(0.6); // slower speed
        spark.setVelocity(dir);
        spark.setGravity(false);
        spark.setItem(new ItemStack(org.bukkit.Material.AIR)); // Invisible projectile

        // Tag for override damage in CombatModule
        spark.getPersistentDataContainer().set(Keys.dmg, PersistentDataType.DOUBLE, spellDmg);

        // Aimbot support for scrolls
        if (aimTier > 0) {
            CombatModule combat = plugin.getModule(CombatModule.class);
            if (combat != null)
                combat.startHomingTask(spark, aimTier);
        } else {
            // Remove after 5s even if not homing
            new BukkitRunnable() {
                @Override
                public void run() {
                    if (!spark.isDead() && spark.isValid())
                        spark.remove();
                }
            }.runTaskLater(plugin, 100L);
        }

        p.playSound(p.getLocation(), Sound.ENTITY_BLAZE_SHOOT, 1f, 1.3f);
        profile.setActionBarMessage(ChatColor.GOLD + "🔥 Ashen Spark!", 1500);

        new org.bukkit.scheduler.BukkitRunnable() {
            @Override
            public void run() {
                if (spark.isDead() || !spark.isValid()) {
                    cancel();
                    return;
                }
                // Ash and flame particles
                spark.getWorld().spawnParticle(Particle.ASH, spark.getLocation(), 15, 0.2, 0.2, 0.2, 0.05);
                spark.getWorld().spawnParticle(Particle.FLAME, spark.getLocation(), 2, 0.1, 0.1, 0.1, 0.01);
            }
        }.runTaskTimer(plugin, 1L, 1L);

        // Remove after 5s
        new BukkitRunnable() {
            @Override
            public void run() {
                if (!spark.isDead() && spark.isValid())
                    spark.remove();
            }
        }.runTaskLater(plugin, 100L);
    }

    // ==========================================
    // SPELL: Little Phoenix (Scroll — Consumable)
    // Gradually regenerates 50% of player Max HP over 5 seconds.
    // ==========================================
    private void castLittlePhoenix(Player p, PlayerProfile profile) {
        PlayerModule pdm = ElpixEdge.getInstance().getModule(PlayerModule.class);
        Attribute maxHpAttr = pdm != null ? pdm.getHealthAttribute() : Attribute.MAX_HEALTH;
        double maxHp = p.getAttribute(maxHpAttr) != null ? p.getAttribute(maxHpAttr).getBaseValue() : 20.0;

        double totalHeal = maxHp * 0.50; // 50% Max HP
        int ticks = 5; // over 5 seconds (5 pulses, 1 per second)
        double healPerTick = totalHeal / ticks;

        p.getWorld().spawnParticle(Particle.FLAME, p.getLocation().add(0, 1, 0), 30, 0.5, 0.5, 0.5, 0.05);
        p.playSound(p.getLocation(), Sound.ENTITY_BLAZE_BURN, 1f, 1.2f);
        profile.setActionBarMessage(ChatColor.RED + "🔥 Little Phoenix — Regenerating...", 6000);

        new BukkitRunnable() {
            int count = 0;

            @Override
            public void run() {
                if (count >= ticks || p.isDead()) {
                    cancel();
                    if (!p.isDead()) {
                        profile.setActionBarMessage(ChatColor.GREEN + "🔥 Phoenix healing complete!", 2000);
                    }
                    return;
                }
                double newHp = Math.min(maxHp, p.getHealth() + healPerTick);
                p.setHealth(newHp);
                p.getWorld().spawnParticle(Particle.HEART, p.getLocation().add(0, 1.5, 0), 3, 0.3, 0.3, 0.3, 0);
                count++;
            }
        }.runTaskTimer(plugin, 0L, 20L);
    }

    // ==========================================
    // Grimoire scroll management helpers
    // ==========================================

    /** Returns the list of ItemStacks stored in this grimoire bundle. */
    private List<ItemStack> getGrimoireScrollItems(ItemMeta meta) {
        if (meta instanceof org.bukkit.inventory.meta.BundleMeta) {
            return new ArrayList<>(((org.bukkit.inventory.meta.BundleMeta) meta).getItems());
        }
        return new ArrayList<>();
    }

    /** Saves the scroll items and active index back to the bundle. */
    private void saveGrimoireScrollItems(ItemStack item, ItemMeta meta, List<ItemStack> scrollItems, int activeIdx) {
        if (meta instanceof org.bukkit.inventory.meta.BundleMeta) {
            ((org.bukkit.inventory.meta.BundleMeta) meta).setItems(scrollItems);
        }
        meta.getPersistentDataContainer().set(Keys.grimoireActive, PersistentDataType.INTEGER, activeIdx);
        updateGrimoireLoreScrollLine(meta, scrollItems, activeIdx);
        item.setItemMeta(meta);
    }

    /** Cycles to the next scroll in the grimoire. */
    private void cycleGrimoireScroll(Player p, ItemStack item, ItemMeta meta) {
        List<ItemStack> scrollItems = getGrimoireScrollItems(meta);
        if (scrollItems.isEmpty()) {
            p.sendMessage(ChatColor.GRAY + "No scrolls in grimoire.");
            return;
        }
        int active = meta.getPersistentDataContainer().getOrDefault(Keys.grimoireActive, PersistentDataType.INTEGER, 0);
        active = (active + 1) % scrollItems.size();
        saveGrimoireScrollItems(item, meta, scrollItems, active);
        p.updateInventory();

        ItemStack activeItem = scrollItems.get(active);
        if (activeItem != null && activeItem.hasItemMeta()) {
            String scrollId = activeItem.getItemMeta().getPersistentDataContainer().get(Keys.scrollType,
                    PersistentDataType.STRING);
            if (scrollId != null) {
                ConfigurationSection sec = plugin.getConfig().getConfigurationSection("scrolls." + scrollId);
                String scrollName = sec != null
                        ? ChatColor.translateAlternateColorCodes('&', sec.getString("name", scrollId))
                        : scrollId;
                p.playSound(p.getLocation(), Sound.ITEM_BOOK_PAGE_TURN, 1f, 1.2f);

                PlayerModule playerMod = ElpixEdge.getInstance().getModule(PlayerModule.class);
                PlayerProfile profile = playerMod != null ? playerMod.getProfile(p) : null;
                if (profile != null) {
                    profile.setActionBarMessage(ChatColor.AQUA + "Active Spell: " + scrollName, 2000);
                }
            }
        }
    }

    /**
     * Updates the grimoire's lore to show the currently active scroll.
     */
    private void updateGrimoireLoreScrollLine(ItemMeta meta, List<ItemStack> scrollItems, int activeIdx) {
        List<String> lore = meta.hasLore() ? new ArrayList<>(meta.getLore()) : new ArrayList<>();

        lore.removeIf(line -> {
            String stripped = ChatColor.stripColor(line);
            return stripped.startsWith("Slots:") || stripped.startsWith("Active Scroll:")
                    || stripped.startsWith("[Scroll") || stripped.startsWith("▶") || stripped.startsWith("  ");
        });

        if (!scrollItems.isEmpty()) {
            int safeIdx = Math.min(activeIdx, scrollItems.size() - 1);
            ItemStack activeItem = scrollItems.get(safeIdx);
            if (activeItem != null && activeItem.hasItemMeta()) {
                String activeId = activeItem.getItemMeta().getPersistentDataContainer().get(Keys.scrollType,
                        PersistentDataType.STRING);
                if (activeId != null) {
                    ConfigurationSection sec = plugin.getConfig().getConfigurationSection("scrolls." + activeId);
                    String activeName = sec != null
                            ? ChatColor.translateAlternateColorCodes('&', sec.getString("name", activeId))
                            : activeId;
                    lore.add(ChatColor.AQUA + "Active Scroll: " + activeName);
                }
            }

            for (int i = 0; i < scrollItems.size(); i++) {
                ItemStack si = scrollItems.get(i);
                if (si == null || !si.hasItemMeta())
                    continue;
                String sid = si.getItemMeta().getPersistentDataContainer().get(Keys.scrollType,
                        PersistentDataType.STRING);
                if (sid == null)
                    continue;

                ConfigurationSection ssc = plugin.getConfig().getConfigurationSection("scrolls." + sid);
                String sName = ssc != null ? ChatColor.translateAlternateColorCodes('&', ssc.getString("name", sid))
                        : sid;
                String marker = (i == activeIdx) ? ChatColor.GREEN + "▶ " : ChatColor.DARK_GRAY + "  ";
                lore.add(marker + sName);
            }
        }

        meta.setLore(lore);
    }

    // ==========================================
    // Grimoire Insertion — called from ItemModule when a scroll is placed into
    // grimoire
    // This is triggered by the admin spawner
    // "admin:addscroll:<grimoireId>:<scrollId>" action.
    // In-game, scrolls are added via the grimoire GUI (Part 3).
    // ==========================================
    /**
     * Handles inventory interactions for the Bundle-based Grimoire.
     * Prevents non-scroll items from being added and ensures lore stays synced.
     */
    /**
     * Handles inventory interactions for the Bundle-based Grimoire.
     * Prevents non-scroll items from being added and ensures lore stays synced.
     */
    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onGrimoireInventoryClick(org.bukkit.event.inventory.InventoryClickEvent event) {
        ItemStack cursor = event.getCursor();
        ItemStack current = event.getCurrentItem();
        Player p = (Player) event.getWhoClicked();

        // Check if either item is a grimoire
        boolean cursorIsGrim = isGrimoire(cursor);
        boolean currentIsGrim = isGrimoire(current);

        if (!cursorIsGrim && !currentIsGrim)
            return;

        // Block non-scroll items from entering the Grimoire Bundle (REMOVED: Now
        // allowed to put anything)
        ItemStack grimoire = cursorIsGrim ? cursor : current;
        ItemStack potentialScroll = cursorIsGrim ? current : cursor;

        // Enforce slot limit (max stacks)
        if (potentialScroll != null && potentialScroll.getType() != Material.AIR) {
            if (event.getClick() == org.bukkit.event.inventory.ClickType.RIGHT
                    || event.getClick() == org.bukkit.event.inventory.ClickType.LEFT) {
                ItemMeta grimoireMeta = grimoire.getItemMeta();
                if (grimoireMeta != null) {
                    List<ItemStack> currentItems = getGrimoireScrollItems(grimoireMeta);
                    int maxSlots = grimoireMeta.getPersistentDataContainer().getOrDefault(Keys.grimoireSlots,
                            PersistentDataType.INTEGER, 4);

                    // Check for scrollType specifically if it has one
                    String scrollType = null;
                    if (potentialScroll.hasItemMeta()) {
                        scrollType = potentialScroll.getItemMeta().getPersistentDataContainer().get(Keys.scrollType,
                                PersistentDataType.STRING);
                    }

                    boolean alreadyIn = false;
                    for (ItemStack si : currentItems) {
                        if (si != null && si.hasItemMeta()) {
                            String type = si.getItemMeta().getPersistentDataContainer().get(Keys.scrollType,
                                    PersistentDataType.STRING);
                            if (scrollType != null && scrollType.equals(type)) {
                                alreadyIn = true;
                                break;
                            }
                        }
                    }

                    if (!alreadyIn && currentItems.size() >= maxSlots) {
                        p.sendMessage(ChatColor.RED + "Grimoire is full! Max slots: " + maxSlots);
                        event.setCancelled(true);
                        return;
                    }
                }
            }
        }

        // Sync lore after interaction (delayed to catch vanilla bundle logic)
        scheduleLoreUpdate(p, grimoire);
    }

    private boolean isGrimoire(ItemStack item) {
        if (item == null || !item.hasItemMeta())
            return false;
        ItemMeta meta = item.getItemMeta();
        return meta.getPersistentDataContainer().has(Keys.magicDmgItem, PersistentDataType.BYTE)
                && !meta.getPersistentDataContainer().has(Keys.offhandTag, PersistentDataType.BYTE)
                && meta.getPersistentDataContainer().has(Keys.grimoireSlots, PersistentDataType.INTEGER);
    }

    private boolean isMenuItem(ItemStack item) {
        if (item == null || !item.hasItemMeta())
            return false;
        String skill = item.getItemMeta().getPersistentDataContainer().get(Keys.skill, PersistentDataType.STRING);
        return "OPEN_MENU".equalsIgnoreCase(skill) || "SUPER_ADMIN".equalsIgnoreCase(skill);
    }

    /**
     * Early-priority guard: prevents Bundle (Grimoire) from spilling items
     * when the player right-clicks with a menu_book or admin_book in main hand.
     */
    @EventHandler(priority = EventPriority.LOWEST)
    public void onBundleProtection(PlayerInteractEvent event) {
        if (event.getAction() != Action.RIGHT_CLICK_AIR && event.getAction() != Action.RIGHT_CLICK_BLOCK)
            return;
        Player p = event.getPlayer();
        ItemStack mainHand = p.getInventory().getItemInMainHand();
        ItemStack offHand = p.getInventory().getItemInOffHand();
        // If main-hand is a menu item and off-hand is a grimoire (BUNDLE), cancel to prevent spill
        if (isMenuItem(mainHand) && isGrimoire(offHand)) {
            event.setCancelled(true);
        }
    }

    private void scheduleLoreUpdate(Player p, ItemStack grimoire) {
        new BukkitRunnable() {
            @Override
            public void run() {
                if (grimoire == null || !grimoire.hasItemMeta())
                    return;
                ItemMeta meta = grimoire.getItemMeta();
                List<ItemStack> items = getGrimoireScrollItems(meta);
                int active = meta.getPersistentDataContainer().getOrDefault(Keys.grimoireActive,
                        PersistentDataType.INTEGER, 0);
                if (active >= items.size())
                    active = Math.max(0, items.size() - 1);

                saveGrimoireScrollItems(grimoire, meta, items, active);
            }
        }.runTaskLater(plugin, 1L);
    }

    /**
     * Attempts to add a scroll to a grimoire item.
     */
    public boolean addScrollToGrimoire(ItemStack grimoire, ItemStack scroll) {
        if (grimoire == null || !(grimoire.getItemMeta() instanceof org.bukkit.inventory.meta.BundleMeta))
            return false;
        if (scroll == null || !scroll.hasItemMeta())
            return false;

        ItemMeta meta = grimoire.getItemMeta();
        List<ItemStack> items = getGrimoireScrollItems(meta);

        int maxSlots = meta.getPersistentDataContainer().getOrDefault(Keys.grimoireSlots, PersistentDataType.INTEGER,
                4);
        if (items.size() >= maxSlots)
            return false;

        items.add(scroll.clone());
        int active = meta.getPersistentDataContainer().getOrDefault(Keys.grimoireActive, PersistentDataType.INTEGER, 0);
        saveGrimoireScrollItems(grimoire, meta, items, active);
        return true;
    }
}
